### ISSUE TITLE
Photographer is able to set a picture price < 0

### ISSUE THREAD

**Issue by gijshendrikx** [roeldewit/PSE#54]
Validation in entity had to be removed in order to make uploading of pictures possible. However this makes it possible for the photographer to add any price he wants.

**Comment by takcy1980** [comment]
I think this can be added back to the price field @DecimalMin(value="0.01", message="{error_decimal_price}")
The problem was @NotNull(message="{error_decimal_price}")

**Comment by ghost** [comment]
I could also set a default price for uploaded pics in the upload form, that's an easy fix.

**Comment by takcy1980** [comment]
yes, but then still its possible to enter a value smaller than 0

**Comment by ghost** [comment]
I meant that if I did that the original validation can be back in place. It's not pretty, but it works. Just 1 line of code to the upload controller.

**Comment by takcy1980** [comment]
Added @DecimalMin(value="0.01", message="{error_decimal_price}") to Price field in hotfix branch

**Comment by ghost** [comment]
Photo upload now needs 0.01 default price it seems.

**Comment by takcy1980** [comment]
that's weird, I tested it and was able to upload succesfully. will check again

**Comment by ghost** [comment]
In that case its ok, I assigned it to myself so I wouldn't forget checking if it still works.

-----Oorspronkelijk bericht-----
Van: "takcy1980" notifications@github.com
Verzonden: ‎25-‎11-‎2015 16:56
Aan: "roeldewit/PSE" PSE@noreply.github.com
CC: "renevdvorst" vdvorst.rene@gmail.com
Onderwerp: Re: [PSE] Photographer is able to set a picture price < 0 (#54)

that's weird, I tested it and was able to upload succesfully. will check again

**Comment by ghost** [comment]
Verified ok, closing.
