### ISSUE TITLE
Payment status is PAID when payment is not definitive

### ISSUE THREAD

**Issue by rversteegt** [roeldewit/PSE#77]
Mollie option " Nog geen eindstatus" results in payment status to change to PAID even though it is not yet confirmed.

**Comment by rversteegt** [comment]
Same with cancelled transactions.

**Comment by ghost** [comment]
Ja klopt, MolliePaymentStatus wordt opgeslagen in db, dat is de mollie status. Order.Orderstatus is onze interne status die had maar 3 opties PLACED, PAID, PROCESSED daar heb ik toen niets in veranderd ivm eventueel stukmaken andermans code. Als die enum uitgebreid wordt kan ik hem mappen met de enum van mollie.

**Comment by rversteegt** [comment]
Wellicht moeten we de order status vervangen met of de order afgehandeld is of niet. En dat we de mollie payment status gebruiken voor het bepalen of een order betaald is of niet.

**Comment by ghost** [comment]
Ja, klinkt goed. Dinsdag even over hebben? Lijkt me niet heel urgent.

**Comment by rversteegt** [comment]
Dinsdag.

**Comment by rversteegt** [comment]
Fixed.
