### ISSUE TITLE
Photo upload pictures not visible in photosession 

### ISSUE THREAD

**Issue by takcy1980** [roeldewit/PSE#87]
When uploading pictures, the photos are not visible in the session, also the pictures do not reach the the producer dashboard for approval

**Comment by ghost** [comment]
Is ftp configured?

**Comment by takcy1980** [comment]
Good one will check. Thought it would be also possible without ftp

Verstuurd vanaf mijn iPhone

**Comment by ghost** [comment]
No, ftp is needed atm. Might add  visual feedback when server is dead or a debug setting next week but we need the high res upload for the presentation anyway. I put a quick guide on google groups a few weeks ago. 

-----Oorspronkelijk bericht-----
Van: "takcy1980" notifications@github.com
Verzonden: ‎9-‎1-‎2016 15:46
Aan: "roeldewit/PSE" PSE@noreply.github.com
CC: "renevdvorst" vdvorst.rene@gmail.com
Onderwerp: Re: [PSE] Photo upload pictures not visible in photosession  (#87)

Good one will check. Thought it would be also possible without ftp

Verstuurd vanaf mijn iPhone
